fix: Chech the `actions` field in flows when running a trace
kytos-ng/sdntrace_cp pull request #70
Opened 2023-02-06 18:39 UTC by gretelliz

Closes #61 

### Summary

Now, it is checked if `actions` is a field of the flow (https://github.com/kytos-ng/sdntrace_cp/blob/86b466560b449b20028512ad4aa1f632bff8946e/main.py#L238)[See Link].

### Local Tests

Now, when running Sdntrace in a switch that has a Flow without actions:

Create a flow for drop packets (no actions):

```
curl -X POST -H 'Content-type: application/json' -d '{"flows": [{"priority": 10, "match": {"in_port": 60, "dl_vlan": 777}}]}' http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:01
```

Run a trace:

```
curl -H 'Content-type: application/json' -X PUT http://127.0.0.1:8181/api/amlight/sdntrace_cp/trace -d '{"trace": {"switch": {"dpid": "00:00:00:00:00:00:00:01", "in_port": 60}, "eth": {"dl_type": 33024, "dl_vlan": 777}}}
```

Response:

```
{"result":[{"dpid":"00:00:00:00:00:00:00:01","out":null,"port":60,"time":"2023-02-06 13:27:59.390535","type":"starting","vlan":777}]}
```

2023-02-27 21:23 UTC, ajoaoff reviewed
@gretelliz It looks fine, but could you please add a test with a stored flow with no actions?

2023-02-27 21:26 UTC, gretelliz commented
> @gretelliz It looks fine, but could you please add a test with a stored flow with no actions?

@ajoaoff, thank you. Sure, I'll do it.

2023-02-27 22:32 UTC, ajoaoff approved these changes
LGTM

2023-02-28 14:36 UTC, viniarck requested changes
LGTM, but please also update the changelog file. 

Also, let's add an e2e test with an empty action (drop) in topology with at least three switches:

1 S1 2 ---- 1 S2 2 ---- 1 S3

and then on SW1 you push a flow matching port 1 and output port 2, but then on S2 you match on port 1 and empty actions, let's ensure that the output of sdntrace_cp is correctly showing that the trace doesn't complete.

2023-02-28 16:21 UTC, viniarck commented
@gretelliz thanks for updating the changelog, you ended up adding the information on section `2022.3.1`, but this change landing on `master` is considered unreleased. Can you fix/move it please?

2023-02-28 16:30 UTC, gretelliz commented
@viniarck, You are right, my bad.

2023-02-28 16:32 UTC, viniarck commented
> @viniarck, You are right, my bad.

Looks good now, feel free to merge this once the e2e is also ready to land. Thanks.

2023-03-01 17:29 UTC, merged