Improve test coverage on main
kytos-ng/sdntrace_cp pull request #97
Opened 2023-06-09 16:44 UTC by gretelliz

Closes #60 

### Summary

Add unit tests for:

- do_match
- match_flows
- match_and_apply

Now the coverage is 95% on main.py.

### Local Tests

N/A

### End-to-End Tests

N/A

2023-06-09 17:43 UTC, viniarck requested changes
@gretelliz, it's great to have improved unit test for these methods, in total it went up 1%. Asked a change though regarding how tests were written. 

- Since you're at it, make sure to also nuke `tests/helpers.py` since it's not doing anything other than bringing coverage down, which can also closes https://github.com/kytos-ng/sdntrace_cp/issues/27

Also, in terms of house keeping there are still:

- The module `scheduler.py` and its tests are no longer useful, since scheduling capabilities got removed on https://github.com/kytos-ng/sdntrace_cp/pull/95/. Consequentely, `apscheduler` can also get removed from `requirements/in.txt` and `requirements/run.txt` should be regenerated.
- Readme is also outdated since it's still mentions `amlight/scheduler` as a dependency


```
Name                           Stmts   Miss  Cover
--------------------------------------------------
__init__.py                        0      0   100%
main.py                          169     12    93%
scheduler.py                      18      1    94%
settings.py                        2      0   100%
tests/__init__.py                  6      0   100%
tests/helpers.py                  18     18     0%
tests/unit/__init__.py             0      0   100%
tests/unit/test_main.py          331      0   100%
tests/unit/test_scheduler.py      23      2    91%
tests/unit/test_utils.py         189      3    98%
utils.py                          89      5    94%
--------------------------------------------------
TOTAL                            845     41    95%
```

Once the house keeping tasks are also addressed it's expected that it'll bring the total code coverage up

2023-06-09 17:43 UTC, viniarck commented on tests/unit/test_main.py
> +        flow = {'flow': {'match': {'dl_vlan': 10}}}
The test case looks good, but it's repeating many `args` `resp`, the idiomatic way with `pytest` when you need to test against multiple/different inputs is to use the `@pytest.mark.parametrize` decorator, and then parametrize `flow,args,should_match` (dict, dict, bool), take a look [on some unit tests examples from flow_manager for instance if you need a reference](https://github.com/kytos-ng/flow_manager/blob/master/tests/unit/test_match_13.py#L53-L73)

2023-06-09 17:43 UTC, viniarck commented on tests/unit/test_main.py
> +    def test_match_and_apply(self):
Same comment regarding `@pytest.mark.parametrize`, ideally it should be using `parametrize` here for maintainability and readability. You can also parametrize the expected `resp` based on what's expected in terms of `flow, entries, port`

2023-06-09 20:24 UTC, gretelliz commented
@viniarck, total code coverage is 97% now.

2023-06-12 13:32 UTC, viniarck approved these changes
Excellent improved test cov and general house keeping, @gretelliz. 

It's ready to land, but before merging make sure to also update the CHANGELOG mentioning that `apscheduler` is no longer a dependency (in a `Removed` section), since it was a relevant dependency it's important to be highlighted.

2023-06-12 14:51 UTC, merged